version: '3.4'

services:
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}guardapi
    build:
      context: .
      dockerfile: Guard.Api/Dockerfile
      
  bot:
    container_name: bot
    image: ${DOCKER_REGISTRY-}guardbot
    build:
      context: .
      dockerfile: Guard.Bot/Dockerfile
    environment:
        - ApiUrl=http://api
        # - BotSettings__Token=TOKEN

  eval-api:
    container_name: evalapi      
    image: ${DOCKER_REGISTRY-}guardevalapi
    restart: always
    build:
      context: .
      dockerfile: Guard.EvalApi/Dockerfile

  rabbitmq:
    container_name: rabbitmq
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
