version: '3.4'

services:
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}guardapi
    build:
      context: .
      dockerfile: Guard.Api/Dockerfile

  bot:
    container_name: bot
    image: ${DOCKER_REGISTRY-}guardbot
    build:
      context: .
      dockerfile: Guard.Bot/Dockerfile
    environment:
        - ApiUrl=http://api
        # - BotSettings__Token=TOKEN
    
  repl:
    image: ghcr.io/discord-csharp/csharprepl:latest
    restart: always
    read_only: true
    user: www-data
    environment:
      - ASPNETCORE_URLS=http://+:31337
    ports:
      - '31337:31337'
    tmpfs:
      - /tmp
      - /var

