version: '3.4'

services:
  api:
    container_name: api
    image: ${DOCKER_REGISTRY-}guardapi
    build:
      context: .
      dockerfile: Guard.Api/Dockerfile

  bot:
    container_name: bot
    image: ${DOCKER_REGISTRY-}guardbot
    build:
      context: .
      dockerfile: Guard.Bot/Dockerfile
    environment:
        - ApiUrl=http://api
        # - BotSettings__Token=—ﬁƒ¿_“Œ ≈Õ

