version: '3.4'
services:
  botovskixapi:
    build: 
      context: ./botovskixAPI/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
  botovskiy:
    build: 
      context: ./botovskiy
      dockerfile: Dockerfile
    volumes:
      - ./Commands:/app/Commands
